### ISSUE TITLE
Set execution count to null on errors from the pick kernel

### ISSUE THREAD

**Issue by rgbkrk** [nteract/pick#20]
I noticed that we can do a completely spec compliant setting of the execution count to `null` (`None` in python) which allows for us to emit errors like in #19 without having a misleading number:

![image](https://user-images.githubusercontent.com/836375/80829116-6641c700-8b9b-11ea-9e48-ac9259a17dac.png)

What do you think @captainsafia, @MSeal, @willingc?

**Comment by rgbkrk** [comment]
I went ahead and added this into #19

**Comment by captainsafia** [comment]
Seems legit. Is the `0` execution count in the second cell intentional?

**Comment by rgbkrk** [comment]
The `[0]` is intentional. Normally the execution counts start at one. In fact, the "actual" kernel (what we're calling the child kernel) will start at 1, so this "pre-amble" `execution_count` has been set to zero. The classic frontend will only allow numbers greater than or equal to zero as well as `null`.

**Comment by rgbkrk** [comment]
Done in #19
