### ISSUE TITLE
Create registration system

### ISSUE THREAD

**Issue by rgbkrk** [nteract/pick#4]
In the style of papermill registration, create a system that allows us to register how we go from config text to kernel manager options. See `papermill_io.register` as prime examples `papermill_translators.register`.

The initial idea is we create our own magics registration namespace. It would look something like this for a user of the kernel:

```
%%kernel.conda-env-yaml
name: env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - codecov
```

Whereas the implementer has their own package that calls our registration:

```python
pick_kernel.kernels.register("conda-env-yaml", handler)
```

What do you think @MSeal & @willingc?

**Comment by rgbkrk** [comment]
With the `yaml` function for formatting decency on the frontend:

```python
%%kernel.conda-env
yaml('''
name: env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - codecov
''')

**Comment by MSeal** [comment]
I think it's a good idea, makes the interface flexible to be used with pre-existing syntax for configuration options in different organizations and tooling.

**Comment by willingc** [comment]
Oooh nice. I've been doing yaml, toml, json config in most of my work stuff these days.
